### PR TITLE
added a form

### PR DESCRIPTION
**Pull request by humuyar**
/// in this pull request I did these things , for a survey form :
#: I added a HTML file
#: in HTML file I  added a form for Registration
#: config linters for checking the error
#: make a CSS file for changing the format of form

### CODE REVIEW

**Comment by humuyar** [comment]
i done my project

**Comment by humuyar** [comment]
@ahzamir
i done my survey-form

**Comment by ahzamir** [comment]
### Hi @humuyar 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- I suggest you add some design using a CSS file to your form so you can share some screenshots of it in your LinkedIn account as your proud moment when you have time for it!

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WellDoneGIF

 ## Highlights 🌞
 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Survey Form project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by humuyar** [comment]
@ahzamir 
Thanks you very much sir for everything you have done for me.

**Comment by humuyar** [comment]
@ahzamir 
sir you said i should send it again i send it to you

**Pull request merged**
